# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Temp' do
    
    
    
    
use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
source 'https://github.com/CocoaPods/Specs.git'
pod 'ActionSheetPicker-3.0', '~> 2.2.0'
  # Pods for Temp

end
